### PR TITLE
Wrote SublimeLinter setup FAQ

### PR DESCRIPTION
**Pull request by kelvinma**
Wrote a set up FAQ for getting the SublimeLinter plugins up and running.

These steps worked fine on my machine, and I set it up on some other folks' as well.

### CODE REVIEW

**Comment by jrhorn424** [comment]
Thanks, @kelvinma! I'll add this manually to the wiki.

**Comment by GA-MEB** [comment]
Just to add to this - we should probably also add instructions to ensure that students run the linter in "background" mode, rather than "manual". This can be changed in the package settings for SublimeLinter.

**Comment by jrhorn424** [comment]
Sure, that makes sense. Don't linters run in background mode by default?

**Comment by gaand** [comment]
I believe that background is the default.  Also, we should make sure that students have all appropriate linters installed (e.g., or maybe that's i.e., jshint, rubocop, tidy5, csslint).

**Comment by jrhorn424** [comment]
I believe this has been addressed by changes to the orientation repo. https://github.com/ga-wdi-boston/orientation

**Pull request closed without merging**
